server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    server:
      host: ${SPRING_REDIS_SERVER_HOST}
      port: ${SPRING_REDIS_SERVER_PORT}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
